spring:
    application.name: blogManagementSystem
    datasource:
        url: jdbc:mysql://localhost:3306/blogManagement
        username: root
        password: rootroot
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        generate-ddl: true

    app:
        jwtSecret: Secret123jdgadgqehbaksjbdaigdbdwbqkujhvsXHJVHQDGDBKJCSAdqgdjh
        jwtExpirationMs: 1000000000

logging:
    level:
        org:
            springframework : DEBUG
            hibernate:
                SQL: DEBUG
            security: DEBUG
        com:
            example:
                securitydemo: DEBUG

#    security:
#      user:
#        name: admin
#        password: password
#    datasource:
#      url: jdbc:mysql://localhost:3306/blogManagement
#      username: root
#      password: rootroot
#      driver-class-name: com.mysql.cj.jdbc.Driver
#    jpa:
#      hibernate:
#        ddl-auto: update
#      show-sql: false
#      properties:
#        hibernate:
#          format_sql: true
#      database-platform: org.hibernate.dialect.MySQLDialect
